/* Question bank — GENERATED by pipeline/build_eng_questions.py.
 * Do not edit by hand: every answer here is computed by that script,
 * so an edit made here would not be checked by anything.
 */
window.QQ_DATA = {
 "version": 1,
 "site": "engineering-entrance",
 "dailyGoalXp": 30,
 "heartsPerLesson": 4,
 "xp": {
  "perQuestion": 2,
  "lessonBonus": 10,
  "perfectBonus": 5
 },
 "libraries": [],
 "vizData": {},
 "units": [
  {
   "id": "u_matrices",
   "index": 1,
   "title": "Matrices",
   "subtitle": "From what a matrix is to exam-level determinants.",
   "colour": "#58a6ff",
   "free": true,
   "syllabus": "enrichment",
   "lessons": [
    {
     "id": "m1",
     "title": "What a matrix is",
     "questions": [
      {
       "id": "mx_order",
       "type": "choice",
       "topic": "matrices",
       "prompt": "A matrix has 3 rows and 2 columns. What is its order?",
       "choices": [
        "2 × 3",
        "3 × 2",
        "6 × 1"
       ],
       "answer": 1,
       "answerValue": "3 × 2",
       "explain": "Order is always rows first, then columns — 3 × 2 here. It is worth being fussy about this from the start, because whether two matrices can be multiplied at all is decided entirely by their orders.",
       "viz": "matGrid",
       "vizHint": "Drag the handles to change the shape."
      },
      {
       "id": "mx_entry",
       "type": "number",
       "topic": "matrices",
       "prompt": "For A = [2 1; 3 4], what is the entry a₂₁ (row 2, column 1)?",
       "answerNumber": 3,
       "tolerance": 0,
       "answerValue": "3",
       "explain": "Row 2, column 1 is 3. The subscripts are row-then-column, the same order as the matrix's own dimensions. Reading them the other way round is the commonest slip in the whole topic.",
       "viz": "matGrid",
       "vizHint": "Tap an entry to see its address."
      },
      {
       "id": "mx_add",
       "type": "number",
       "topic": "matrices",
       "prompt": "A = [2 1; 3 4] and B = [1 0; -2 5]. What is the top-left entry of A + B?",
       "answerNumber": 3,
       "tolerance": 0,
       "answerValue": "3",
       "explain": "Addition is entry by entry: 2 + 1 = 3. Two matrices can only be added if they have exactly the same order, because every entry needs a partner.",
       "viz": "matGrid"
      },
      {
       "id": "mx_add_order",
       "type": "truefalse",
       "topic": "matrices",
       "prompt": "A 2 × 3 matrix can be added to a 3 × 2 matrix.",
       "statement": "A 2 × 3 matrix can be added to a 3 × 2 matrix.",
       "answerBool": false,
       "answerValue": "FALSE",
       "explain": "They have the same six entries but not the same shape, and addition pairs entries by position. No pairing exists, so the sum is undefined. (Multiplication is a different story — see the next lesson.)"
      },
      {
       "id": "mx_scalar",
       "type": "number",
       "topic": "matrices",
       "prompt": "What is the bottom-right entry of 3A, where A = [2 1; 3 4]?",
       "answerNumber": 12,
       "tolerance": 0,
       "answerValue": "12",
       "explain": "A scalar multiplies every entry: 3 × 4 = 12. Scaling a matrix scales everything it does — a transformation matrix multiplied by 3 stretches three times as much.",
       "viz": "matGrid"
      }
     ]
    },
    {
     "id": "m2",
     "title": "Multiplying matrices",
     "questions": [
      {
       "id": "mx_conform",
       "type": "choice",
       "topic": "matrices",
       "prompt": "Which product is defined: a 2 × 3 matrix times a 3 × 4 matrix, or a 3 × 4 times a 2 × 3?",
       "choices": [
        "2×3 times 3×4",
        "3×4 times 2×3",
        "Both",
        "Neither"
       ],
       "answer": 0,
       "answerValue": "2×3 times 3×4",
       "explain": "The inner numbers must match: (2 × 3)(3 × 4) works because the 3s meet, and the result is 2 × 4 — the outer numbers. The other way round, 4 and 2 do not match, so nothing is defined.",
       "viz": "matMul",
       "vizHint": "Slide the shapes together to see which fit."
      },
      {
       "id": "mx_entry11",
       "type": "number",
       "topic": "matrices",
       "prompt": "A = [2 1; 3 4], B = [1 0; -2 5]. What is the top-left entry of AB?",
       "answerNumber": 0,
       "tolerance": 0,
       "answerValue": "0",
       "explain": "Row 1 of A against column 1 of B: 2×1 + 1×-2 = 0. Every entry of a product is one row dotted with one column, and that is the whole rule.",
       "viz": "matMul",
       "vizHint": "Tap an entry of the answer to see which row and column build it."
      },
      {
       "id": "mx_entry22",
       "type": "number",
       "topic": "matrices",
       "prompt": "For the same A and B, what is the bottom-right entry of AB?",
       "answerNumber": 20,
       "tolerance": 0,
       "answerValue": "20",
       "explain": "Row 2 of A against column 2 of B: 3×0 + 4×5 = 20. Notice you never touch the other row or the other column — each entry of the product is built from exactly one of each, which is why the result is 2 × 2 rather than anything larger.",
       "viz": "matMul"
      },
      {
       "id": "mx_commute",
       "type": "truefalse",
       "topic": "matrices",
       "prompt": "For matrices, AB is always the same as BA.",
       "statement": "For matrices, AB is always the same as BA.",
       "answerBool": false,
       "answerValue": "FALSE",
       "explain": "It is usually not. With A = [2 1; 3 4] and B = [1 0; -2 5], AB = [0 5; -5 20] but BA = [2 1; 11 18]. Order matters because matrices are transformations, and rotating then reflecting is not the same as reflecting then rotating. This is the single most tested fact in the topic.",
       "viz": "matMul"
      },
      {
       "id": "mx_identity",
       "type": "number",
       "topic": "matrices",
       "prompt": "What is the top-left entry of A × I, where A = [2 1; 3 4] and I is the 2 × 2 identity?",
       "answerNumber": 2,
       "tolerance": 0,
       "answerValue": "2",
       "explain": "The identity changes nothing: AI = IA = A. It is the matrix version of multiplying by 1, and it is the reason an inverse is defined as the matrix that gets you back to I."
      }
     ]
    },
    {
     "id": "m3",
     "title": "Determinants",
     "questions": [
      {
       "id": "mx_det2",
       "type": "number",
       "topic": "matrices",
       "prompt": "Find the determinant of [3 4; 1 2].",
       "answerNumber": 2,
       "tolerance": 0,
       "answerValue": "2",
       "explain": "ad − bc = 3×2 − 4×1 = 2. The determinant is the factor by which the matrix scales area: a unit square is sent to a parallelogram of area 2.",
       "viz": "detArea",
       "vizHint": "Drag the two column vectors and watch the area change."
      },
      {
       "id": "mx_det_singular",
       "type": "number",
       "topic": "matrices",
       "prompt": "Find the determinant of [2 6; 1 3].",
       "answerNumber": 0,
       "tolerance": 0,
       "answerValue": "0",
       "explain": "2×3 − 6×1 = 0. A zero determinant means the two columns lie on the same line, so the unit square is squashed flat onto a line — area zero. Such a matrix is called singular and has no inverse.",
       "viz": "detArea"
      },
      {
       "id": "mx_det_zero_inv",
       "type": "truefalse",
       "topic": "matrices",
       "prompt": "A matrix with determinant zero still has an inverse.",
       "statement": "A matrix with determinant zero still has an inverse.",
       "answerBool": false,
       "answerValue": "FALSE",
       "explain": "It cannot. The inverse divides by the determinant, and more fundamentally a singular matrix collapses the plane onto a line — information is destroyed, so there is no way back. Every point on that line has infinitely many origins.",
       "viz": "detArea"
      },
      {
       "id": "mx_det_neg",
       "type": "number",
       "topic": "matrices",
       "prompt": "A matrix sends the unit square to a parallelogram of area 6, flipping its orientation. What is its determinant?",
       "answerNumber": -6,
       "tolerance": 0,
       "answerValue": "-6",
       "explain": "Magnitude 6 for the area, negative for the flip. The SIGN of a determinant records whether the transformation preserves orientation — a reflection has a negative determinant, a rotation a positive one.",
       "viz": "detArea"
      },
      {
       "id": "mx_det3",
       "type": "number",
       "topic": "matrices",
       "prompt": "Find the determinant of the 3 × 3 matrix [1 2 3; 0 1 4; 5 6 0].",
       "answerNumber": 1,
       "tolerance": 0,
       "answerValue": "1",
       "explain": "Expanding along the top row: 1(1×0 − 4×6) − 2(0×0 − 4×5) + 3(0×6 − 1×5) = 1(−24) − 2(−20) + 3(−5) = −24 + 40 − 15 = 1. Watch the alternating signs + − + across the row; forgetting the middle minus is the standard way to lose the mark."
      }
     ]
    },
    {
     "id": "m4",
     "title": "Inverses and solving equations",
     "questions": [
      {
       "id": "mx_inv_a",
       "type": "number",
       "topic": "matrices",
       "prompt": "For M = [3 4; 1 2], the inverse is (1/det)·[d −b; −c a]. What is the top-left entry of M⁻¹?",
       "answerNumber": 1,
       "tolerance": 0,
       "answerValue": "1",
       "explain": "Swap the diagonal, negate the off-diagonal, divide by the determinant 2: top-left becomes 2/2 = 1.",
       "viz": "matInv",
       "vizHint": "Watch the inverse undo the transformation."
      },
      {
       "id": "mx_inv_check",
       "type": "truefalse",
       "topic": "matrices",
       "prompt": "Multiplying a matrix by its inverse gives the identity, in either order.",
       "statement": "Multiplying a matrix by its inverse gives the identity, in either order.",
       "answerBool": true,
       "answerValue": "TRUE",
       "explain": "MM⁻¹ = M⁻¹M = I. Inverses are the one case where matrix multiplication does commute, and that is essentially what being an inverse means.",
       "viz": "matInv"
      },
      {
       "id": "mx_solve_x",
       "type": "number",
       "topic": "matrices",
       "prompt": "Solve 3x + 4y = 10 and x + 2y = 4 using matrices. What is x?",
       "answerNumber": 2,
       "tolerance": 0,
       "answerValue": "2",
       "explain": "The system is [3 4; 1 2][x; y] = [10; 4]. The determinant is 3×2 − 4×1 = 2, so the inverse is (1/2)[2 −4; −1 3]. Multiplying: x = (2×10 − 4×4)/2 = 4/2 = 2, and y = (−1×10 + 3×4)/2 = 2/2 = 1. Check: 3(2) + 4(1) = 10. ✓",
       "viz": "solveLines",
       "vizHint": "Drag the lines; the crossing point is the solution."
      },
      {
       "id": "mx_solve_y",
       "type": "number",
       "topic": "matrices",
       "prompt": "For the same system, what is y?",
       "answerNumber": 1,
       "tolerance": 0,
       "answerValue": "1",
       "explain": "y = 1, from (−1×10 + 3×4)/2 = 1. Both original equations check out: 3(2)+4(1) = 10 and 2 + 2(1) = 4.",
       "viz": "solveLines"
      },
      {
       "id": "mx_singular_system",
       "type": "choice",
       "topic": "matrices",
       "prompt": "A 2 × 2 system has determinant zero. What does that tell you about the two lines?",
       "choices": [
        "They cross at exactly one point",
        "They are parallel — no solution, or the same line with infinitely many",
        "They are perpendicular"
       ],
       "answer": 1,
       "answerValue": "They are parallel — no solution, or the same line with infinitely many",
       "explain": "Zero determinant means the rows are multiples of each other, so the two lines have the same gradient. Either they never meet (no solutions) or they are the same line (infinitely many). Exactly one solution is precisely what a non-zero determinant guarantees.",
       "viz": "solveLines"
      }
     ]
    },
    {
     "id": "m5",
     "title": "Matrices as transformations",
     "questions": [
      {
       "id": "mx_rot90",
       "type": "choice",
       "topic": "matrices",
       "prompt": "Which matrix rotates the plane 90° anticlockwise about the origin?",
       "choices": [
        "[0 −1; 1 0]",
        "[0 1; −1 0]",
        "[−1 0; 0 −1]"
       ],
       "answer": 0,
       "answerValue": "[0 −1; 1 0]",
       "explain": "Track where the basis vectors go. (1,0) must land on (0,1) and (0,1) on (−1,0) — and those images ARE the columns of the matrix. That trick answers every transformation-matrix question without memorising anything.",
       "viz": "transformPlane",
       "vizHint": "Drag the sliders and watch the shape move."
      },
      {
       "id": "mx_reflect_det",
       "type": "number",
       "topic": "matrices",
       "prompt": "What is the determinant of the matrix that reflects in the x-axis, [1 0; 0 −1]?",
       "answerNumber": -1,
       "tolerance": 0,
       "answerValue": "-1",
       "explain": "1×(−1) − 0×0 = −1. Area is preserved (magnitude 1) but orientation is reversed (negative) — which is exactly what a reflection does.",
       "viz": "transformPlane"
      },
      {
       "id": "mx_enlarge",
       "type": "number",
       "topic": "matrices",
       "prompt": "An enlargement scale factor 3 about the origin has matrix [3 0; 0 3]. By what factor does it multiply AREA?",
       "answerNumber": 9,
       "tolerance": 0,
       "answerValue": "9",
       "explain": "det = 9. Lengths triple, so areas go up by 3² = 9. In general a 2 × 2 matrix multiplies area by |det|, which is the cleanest way to remember what a determinant is FOR.",
       "viz": "detArea"
      },
      {
       "id": "mx_compose_order",
       "type": "choice",
       "topic": "matrices",
       "prompt": "You rotate by R and then reflect by F. Which single matrix does the job?",
       "choices": [
        "RF",
        "FR",
        "R + F"
       ],
       "answer": 1,
       "answerValue": "FR",
       "explain": "FR — the one applied FIRST sits nearest the vector, on the right, because it acts on the vector first: F(Rv) = (FR)v. Reading composition left to right is the classic error, and it gives a different transformation whenever the two do not commute.",
       "viz": "transformPlane"
      },
      {
       "id": "mx_shear_area",
       "type": "number",
       "topic": "matrices",
       "prompt": "A shear has matrix [1 4; 0 1]. What is its determinant?",
       "answerNumber": 1,
       "tolerance": 0,
       "answerValue": "1",
       "explain": "1×1 − 4×0 = 1. A shear slides the plane sideways but preserves area entirely — the parallelogram leans over without getting bigger. Determinant 1 is the signature of that.",
       "viz": "detArea"
      }
     ]
    },
    {
     "id": "m6",
     "title": "Exam-level problems",
     "questions": [
      {
       "id": "mx_det_product",
       "type": "number",
       "topic": "matrices",
       "prompt": "det(A) = 3 and det(B) = 5, both 2 × 2. What is det(AB)?",
       "answerNumber": 15,
       "tolerance": 0,
       "answerValue": "15",
       "explain": "det(AB) = det(A)det(B) = 15. It follows from what determinants mean: apply one transformation that triples area, then one that quintuples it, and area is multiplied by 15. This identity is worth knowing cold — it turns many exam questions into one line.",
       "viz": "detArea"
      },
      {
       "id": "mx_det_inverse",
       "type": "number",
       "topic": "matrices",
       "prompt": "det(A) = 4. What is det(A⁻¹)? Give your answer as a decimal.",
       "answerNumber": 0.25,
       "tolerance": 0.001,
       "answerValue": "0.25",
       "explain": "Since AA⁻¹ = I and det(I) = 1, det(A)det(A⁻¹) = 1, so det(A⁻¹) = 1/4 = 0.25. The inverse must undo the area scaling."
      },
      {
       "id": "mx_det_scalar",
       "type": "number",
       "topic": "matrices",
       "prompt": "A is 2 × 2 with det(A) = 3. What is det(2A)?",
       "answerNumber": 12,
       "tolerance": 0,
       "answerValue": "12",
       "explain": "Every entry doubles, so BOTH columns double, and area scales by 2 × 2 = 4. det(2A) = 4 × 3 = 12. For an n × n matrix the factor is kⁿ — a favourite exam trap, because the instinct is to say 6.",
       "viz": "detArea"
      },
      {
       "id": "mx_lambda",
       "type": "number",
       "topic": "matrices",
       "prompt": "For what value of k is [k 3; 2 k−1] singular? Give the positive root.",
       "answerNumber": 3,
       "tolerance": 0,
       "answerValue": "3",
       "explain": "Singular means determinant zero: k(k−1) − 6 = 0, so k² − k − 6 = 0, giving (k−3)(k+2) = 0 and k = 3 or k = −2. The positive root is 3. Check: [3 3; 2 2] has rows in the ratio 1 : 1, plainly singular."
      },
      {
       "id": "mx_transpose_det",
       "type": "truefalse",
       "topic": "matrices",
       "prompt": "A matrix and its transpose have the same determinant.",
       "statement": "A matrix and its transpose have the same determinant.",
       "answerBool": true,
       "answerValue": "TRUE",
       "explain": "det(Aᵀ) = det(A) always. For a 2 × 2 it is immediate: swapping b and c leaves ad − bc alone. It is the reason you may expand a determinant along a column just as happily as along a row."
      }
     ]
    }
   ]
  },
  {
   "id": "u_algebra",
   "index": 2,
   "title": "Algebra and functions",
   "subtitle": "Indices, surds, quadratics, polynomials.",
   "colour": "#3fb950",
   "free": true,
   "syllabus": "ESAT M1 · PAT",
   "lessons": [
    {
     "id": "a1",
     "title": "Indices and surds",
     "questions": [
      {
       "id": "al_indices",
       "type": "number",
       "topic": "algebra",
       "prompt": "Simplify (2³)⁴ ÷ 2¹⁰ as a power of 2. What is the index?",
       "answerNumber": 2,
       "tolerance": 0,
       "answerValue": "2",
       "explain": "(2³)⁴ = 2¹² and 2¹² ÷ 2¹⁰ = 2². Multiply indices when raising a power to a power, subtract when dividing."
      },
      {
       "id": "al_surd",
       "type": "number",
       "topic": "algebra",
       "prompt": "Rationalise 6/√3 and give the coefficient of √3.",
       "answerNumber": 2,
       "tolerance": 0,
       "answerValue": "2",
       "explain": "Multiply top and bottom by √3: 6√3/3 = 2√3, so the coefficient is 2. Rationalising never changes the value, only the form — and examiners expect the form with no surd underneath."
      },
      {
       "id": "al_quad_roots",
       "type": "number",
       "topic": "algebra",
       "prompt": "How many real roots does x² − 6x + 9 = 0 have?",
       "answerNumber": 1,
       "tolerance": 0,
       "answerValue": "1",
       "explain": "The discriminant is 36 − 36 = 0, so there is one repeated root, x = 3. b² − 4ac decides it: positive two, zero one, negative none."
      },
      {
       "id": "al_complete",
       "type": "number",
       "topic": "algebra",
       "prompt": "Write x² + 8x + 3 as (x + p)² + q. What is q?",
       "answerNumber": -13,
       "tolerance": 0,
       "answerValue": "-13",
       "explain": "Half of 8 is 4, so (x+4)² = x² + 8x + 16, which overshoots by 13. Hence (x+4)² − 13 and q = −13. Completing the square hands you the minimum point directly: (−4, −13)."
      },
      {
       "id": "al_disc",
       "type": "truefalse",
       "topic": "algebra",
       "prompt": "If a quadratic has a negative discriminant its graph never crosses the x-axis.",
       "statement": "If a quadratic has a negative discriminant its graph never crosses the x-axis.",
       "answerBool": true,
       "answerValue": "TRUE",
       "explain": "No real roots means no crossings — the parabola sits entirely above or entirely below the axis, depending on the sign of a."
      }
     ]
    }
   ]
  },
  {
   "id": "u_calculus",
   "index": 3,
   "title": "Differentiation",
   "subtitle": "Rates of change, stationary points, optimisation.",
   "colour": "#d29922",
   "free": false,
   "syllabus": "ESAT M1 · PAT",
   "lessons": [
    {
     "id": "c1",
     "title": "Differentiating",
     "questions": [
      {
       "id": "ca_power",
       "type": "number",
       "topic": "calculus",
       "prompt": "Differentiate y = 4x³. What is dy/dx when x = 2?",
       "answerNumber": 48,
       "tolerance": 0,
       "answerValue": "48",
       "explain": "dy/dx = 12x², and 12 × 4 = 48. Multiply by the index, then drop it by one."
      },
      {
       "id": "ca_stationary",
       "type": "number",
       "topic": "calculus",
       "prompt": "y = x² − 6x + 5. At what value of x is the stationary point?",
       "answerNumber": 3,
       "tolerance": 0,
       "answerValue": "3",
       "explain": "dy/dx = 2x − 6 = 0 gives x = 3. The second derivative is 2, positive, so it is a minimum."
      },
      {
       "id": "ca_tangent",
       "type": "number",
       "topic": "calculus",
       "prompt": "Find the gradient of the tangent to y = x³ − 2x at x = 1.",
       "answerNumber": 1,
       "tolerance": 0,
       "answerValue": "1",
       "explain": "dy/dx = 3x² − 2, which is 3 − 2 = 1 at x = 1. The derivative IS the gradient function: feed it an x and it hands back the slope of the tangent at that point."
      },
      {
       "id": "ca_chain",
       "type": "number",
       "topic": "calculus",
       "prompt": "Differentiate y = (2x + 1)⁵ and give dy/dx at x = 0.",
       "answerNumber": 10,
       "tolerance": 0,
       "answerValue": "10",
       "explain": "Chain rule: dy/dx = 5(2x+1)⁴ × 2 = 10(2x+1)⁴, which is 10 at x = 0."
      },
      {
       "id": "ca_second",
       "type": "truefalse",
       "topic": "calculus",
       "prompt": "A stationary point with a positive second derivative is a minimum.",
       "statement": "A stationary point with a positive second derivative is a minimum.",
       "answerBool": true,
       "answerValue": "TRUE",
       "explain": "Positive second derivative means the gradient is increasing through the point, so the curve turns upward — a minimum."
      }
     ]
    }
   ]
  },
  {
   "id": "u_mechanics",
   "index": 4,
   "title": "Mechanics",
   "subtitle": "Kinematics, forces, momentum, energy.",
   "colour": "#f85149",
   "free": false,
   "syllabus": "ESAT Physics · PAT",
   "lessons": [
    {
     "id": "p1",
     "title": "Motion and forces",
     "questions": [
      {
       "id": "me_suvat",
       "type": "number",
       "topic": "mechanics",
       "prompt": "A ball is dropped from rest. Taking g = 10 m/s², how fast is it moving after 3 s, in m/s?",
       "answerNumber": 30,
       "tolerance": 0,
       "answerValue": "30",
       "explain": "v = u + at = 0 + 10×3 = 30 m/s. With u = 0 the suvat equations become very short — worth spotting."
      },
      {
       "id": "me_distance",
       "type": "number",
       "topic": "mechanics",
       "prompt": "Same ball, same g = 10. How far has it fallen in 3 s, in metres?",
       "answerNumber": 45,
       "tolerance": 0,
       "answerValue": "45",
       "explain": "s = ut + ½at² = 0 + ½×10×9 = 45 m. Distance grows with the SQUARE of time, which is why the last second of a fall covers the most ground."
      },
      {
       "id": "me_newton",
       "type": "number",
       "topic": "mechanics",
       "prompt": "A 4 kg mass accelerates at 2.5 m/s². What resultant force acts on it, in newtons?",
       "answerNumber": 10,
       "tolerance": 0,
       "answerValue": "10",
       "explain": "F = ma = 4 × 2.5 = 10 N. The word RESULTANT matters: it is the vector sum of every force, not any single one."
      },
      {
       "id": "me_momentum",
       "type": "number",
       "topic": "mechanics",
       "prompt": "A 2 kg trolley at 3 m/s hits a stationary 1 kg trolley and they move off together. What is their common speed, in m/s?",
       "answerNumber": 2,
       "tolerance": 0,
       "answerValue": "2",
       "explain": "Momentum before = 2×3 = 6 kg m/s. After, the combined mass is 3 kg, so v = 6/3 = 2 m/s. Momentum is conserved in every collision; kinetic energy is not."
      },
      {
       "id": "me_ke_conserved",
       "type": "truefalse",
       "topic": "mechanics",
       "prompt": "Kinetic energy is conserved when two objects stick together in a collision.",
       "statement": "Kinetic energy is conserved when two objects stick together in a collision.",
       "answerBool": false,
       "answerValue": "FALSE",
       "explain": "That is a perfectly inelastic collision — momentum is conserved, kinetic energy is not. Some of it becomes heat, sound and deformation. Here: 9 J before, 6 J after."
      }
     ]
    }
   ]
  },
  {
   "id": "u_electricity",
   "index": 5,
   "title": "Electricity",
   "subtitle": "Current, resistance, circuits, power.",
   "colour": "#a371f7",
   "free": false,
   "syllabus": "ESAT Physics · PAT",
   "lessons": [
    {
     "id": "e1",
     "title": "Circuits",
     "questions": [
      {
       "id": "el_ohm",
       "type": "number",
       "topic": "electricity",
       "prompt": "A 12 V supply drives 3 A through a resistor. What is its resistance, in ohms?",
       "answerNumber": 4,
       "tolerance": 0,
       "answerValue": "4",
       "explain": "R = V/I = 12/3 = 4 Ω. Ohm's law rearranges three ways and the exam will use all of them, so it is worth being able to write any one of V, I, R in terms of the other two without stopping to think."
      },
      {
       "id": "el_series",
       "type": "number",
       "topic": "electricity",
       "prompt": "Resistors of 3 Ω and 5 Ω in series. What is the total resistance, in ohms?",
       "answerNumber": 8,
       "tolerance": 0,
       "answerValue": "8",
       "explain": "In series resistances simply add: 8 Ω. The same current passes through both."
      },
      {
       "id": "el_parallel",
       "type": "number",
       "topic": "electricity",
       "prompt": "Two 6 Ω resistors in parallel. What is the total resistance, in ohms?",
       "answerNumber": 3,
       "tolerance": 0,
       "answerValue": "3",
       "explain": "1/R = 1/6 + 1/6 = 1/3, so R = 3 Ω. Two equal resistors in parallel always give half of one — a shortcut worth having."
      },
      {
       "id": "el_power",
       "type": "number",
       "topic": "electricity",
       "prompt": "A 240 V kettle draws 8 A. What is its power, in watts?",
       "answerNumber": 1920,
       "tolerance": 0,
       "answerValue": "1920",
       "explain": "P = VI = 240 × 8 = 1920 W, near enough 2 kW. The other two forms, P = I²R and P = V²/R, follow by substituting Ohm's law and are often quicker when you know the resistance instead of one of the other quantities."
      },
      {
       "id": "el_parallel_less",
       "type": "truefalse",
       "topic": "electricity",
       "prompt": "Adding a resistor in parallel always decreases the total resistance.",
       "statement": "Adding a resistor in parallel always decreases the total resistance.",
       "answerBool": true,
       "answerValue": "TRUE",
       "explain": "Another parallel path gives the current somewhere else to go, so the combination always conducts better than the best single branch."
      }
     ]
    }
   ]
  }
 ]
};
