/* Question bank — GENERATED by pipeline/build_eng_questions.py.
 * Do not edit by hand: every answer here is computed by that script,
 * so an edit made here would not be checked by anything.
 */
window.QQ_DATA = {
 "version": 1,
 "site": "engineering-entrance",
 "dailyGoalXp": 30,
 "heartsPerLesson": 4,
 "xp": {
  "perQuestion": 2,
  "lessonBonus": 10,
  "perfectBonus": 5
 },
 "libraries": [],
 "vizData": {},
 "units": [
  {
   "id": "u_matrices",
   "index": 1,
   "title": "Matrices",
   "subtitle": "From what a matrix is to exam-level determinants.",
   "colour": "#58a6ff",
   "free": true,
   "syllabus": "enrichment",
   "lessons": [
    {
     "id": "m1",
     "title": "What a matrix is",
     "questions": [
      {
       "id": "mx_order",
       "type": "choice",
       "topic": "matrices",
       "prompt": "A matrix has 3 rows and 2 columns. What is its order?",
       "choices": [
        "2 × 3",
        "3 × 2",
        "6 × 1"
       ],
       "answer": 1,
       "answerValue": "3 × 2",
       "explain": "Order is always rows first, then columns — 3 × 2 here. It is worth being fussy about this from the start, because whether two matrices can be multiplied at all is decided entirely by their orders.",
       "viz": "matGrid",
       "vizHint": "Drag the handles to change the shape."
      },
      {
       "id": "mx_entry",
       "type": "number",
       "topic": "matrices",
       "prompt": "For A = [2 1; 3 4], what is the entry a₂₁ (row 2, column 1)?",
       "answerNumber": 3,
       "tolerance": 0,
       "answerValue": "3",
       "explain": "Row 2, column 1 is 3. The subscripts are row-then-column, the same order as the matrix's own dimensions. Reading them the other way round is the commonest slip in the whole topic.",
       "viz": "matGrid",
       "vizHint": "Tap an entry to see its address."
      },
      {
       "id": "mx_add",
       "type": "number",
       "topic": "matrices",
       "prompt": "A = [2 1; 3 4] and B = [1 0; -2 5]. What is the top-left entry of A + B?",
       "answerNumber": 3,
       "tolerance": 0,
       "answerValue": "3",
       "explain": "Addition is entry by entry: 2 + 1 = 3. Two matrices can only be added if they have exactly the same order, because every entry needs a partner.",
       "viz": "matGrid"
      },
      {
       "id": "mx_add_order",
       "type": "truefalse",
       "topic": "matrices",
       "prompt": "A 2 × 3 matrix can be added to a 3 × 2 matrix.",
       "statement": "A 2 × 3 matrix can be added to a 3 × 2 matrix.",
       "answerBool": false,
       "answerValue": "FALSE",
       "explain": "They have the same six entries but not the same shape, and addition pairs entries by position. No pairing exists, so the sum is undefined. (Multiplication is a different story — see the next lesson.)"
      },
      {
       "id": "mx_scalar",
       "type": "number",
       "topic": "matrices",
       "prompt": "What is the bottom-right entry of 3A, where A = [2 1; 3 4]?",
       "answerNumber": 12,
       "tolerance": 0,
       "answerValue": "12",
       "explain": "A scalar multiplies every entry: 3 × 4 = 12. Scaling a matrix scales everything it does — a transformation matrix multiplied by 3 stretches three times as much.",
       "viz": "matGrid"
      }
     ]
    },
    {
     "id": "m2",
     "title": "Multiplying matrices",
     "questions": [
      {
       "id": "mx_conform",
       "type": "choice",
       "topic": "matrices",
       "prompt": "Which product is defined: a 2 × 3 matrix times a 3 × 4 matrix, or a 3 × 4 times a 2 × 3?",
       "choices": [
        "2×3 times 3×4",
        "3×4 times 2×3",
        "Both",
        "Neither"
       ],
       "answer": 0,
       "answerValue": "2×3 times 3×4",
       "explain": "The inner numbers must match: (2 × 3)(3 × 4) works because the 3s meet, and the result is 2 × 4 — the outer numbers. The other way round, 4 and 2 do not match, so nothing is defined.",
       "viz": "matMul",
       "vizHint": "Slide the shapes together to see which fit."
      },
      {
       "id": "mx_entry11",
       "type": "number",
       "topic": "matrices",
       "prompt": "A = [2 1; 3 4], B = [1 0; -2 5]. What is the top-left entry of AB?",
       "answerNumber": 0,
       "tolerance": 0,
       "answerValue": "0",
       "explain": "Row 1 of A against column 1 of B: 2×1 + 1×-2 = 0. Every entry of a product is one row dotted with one column, and that is the whole rule.",
       "viz": "matMul",
       "vizHint": "Tap an entry of the answer to see which row and column build it."
      },
      {
       "id": "mx_entry22",
       "type": "number",
       "topic": "matrices",
       "prompt": "For the same A and B, what is the bottom-right entry of AB?",
       "answerNumber": 20,
       "tolerance": 0,
       "answerValue": "20",
       "explain": "Row 2 of A against column 2 of B: 3×0 + 4×5 = 20. Notice you never touch the other row or the other column — each entry of the product is built from exactly one of each, which is why the result is 2 × 2 rather than anything larger.",
       "viz": "matMul"
      },
      {
       "id": "mx_commute",
       "type": "truefalse",
       "topic": "matrices",
       "prompt": "For matrices, AB is always the same as BA.",
       "statement": "For matrices, AB is always the same as BA.",
       "answerBool": false,
       "answerValue": "FALSE",
       "explain": "It is usually not. With A = [2 1; 3 4] and B = [1 0; -2 5], AB = [0 5; -5 20] but BA = [2 1; 11 18]. Order matters because matrices are transformations, and rotating then reflecting is not the same as reflecting then rotating. This is the single most tested fact in the topic.",
       "viz": "matMul"
      },
      {
       "id": "mx_identity",
       "type": "number",
       "topic": "matrices",
       "prompt": "What is the top-left entry of A × I, where A = [2 1; 3 4] and I is the 2 × 2 identity?",
       "answerNumber": 2,
       "tolerance": 0,
       "answerValue": "2",
       "explain": "The identity changes nothing: AI = IA = A. It is the matrix version of multiplying by 1, and it is the reason an inverse is defined as the matrix that gets you back to I."
      }
     ]
    },
    {
     "id": "m3",
     "title": "Determinants",
     "questions": [
      {
       "id": "mx_det2",
       "type": "number",
       "topic": "matrices",
       "prompt": "Find the determinant of [3 4; 1 2].",
       "answerNumber": 2,
       "tolerance": 0,
       "answerValue": "2",
       "explain": "ad − bc = 3×2 − 4×1 = 2. The determinant is the factor by which the matrix scales area: a unit square is sent to a parallelogram of area 2.",
       "viz": "detArea",
       "vizHint": "Drag the two column vectors and watch the area change."
      },
      {
       "id": "mx_det_singular",
       "type": "number",
       "topic": "matrices",
       "prompt": "Find the determinant of [2 6; 1 3].",
       "answerNumber": 0,
       "tolerance": 0,
       "answerValue": "0",
       "explain": "2×3 − 6×1 = 0. A zero determinant means the two columns lie on the same line, so the unit square is squashed flat onto a line — area zero. Such a matrix is called singular and has no inverse.",
       "viz": "detArea"
      },
      {
       "id": "mx_det_zero_inv",
       "type": "truefalse",
       "topic": "matrices",
       "prompt": "A matrix with determinant zero still has an inverse.",
       "statement": "A matrix with determinant zero still has an inverse.",
       "answerBool": false,
       "answerValue": "FALSE",
       "explain": "It cannot. The inverse divides by the determinant, and more fundamentally a singular matrix collapses the plane onto a line — information is destroyed, so there is no way back. Every point on that line has infinitely many origins.",
       "viz": "detArea"
      },
      {
       "id": "mx_det_neg",
       "type": "number",
       "topic": "matrices",
       "prompt": "A matrix sends the unit square to a parallelogram of area 6, flipping its orientation. What is its determinant?",
       "answerNumber": -6,
       "tolerance": 0,
       "answerValue": "-6",
       "explain": "Magnitude 6 for the area, negative for the flip. The SIGN of a determinant records whether the transformation preserves orientation — a reflection has a negative determinant, a rotation a positive one.",
       "viz": "detArea"
      },
      {
       "id": "mx_det3",
       "type": "number",
       "topic": "matrices",
       "prompt": "Find the determinant of the 3 × 3 matrix [1 2 3; 0 1 4; 5 6 0].",
       "answerNumber": 1,
       "tolerance": 0,
       "answerValue": "1",
       "explain": "Expanding along the top row: 1(1×0 − 4×6) − 2(0×0 − 4×5) + 3(0×6 − 1×5) = 1(−24) − 2(−20) + 3(−5) = −24 + 40 − 15 = 1. Watch the alternating signs + − + across the row; forgetting the middle minus is the standard way to lose the mark."
      }
     ]
    },
    {
     "id": "m4",
     "title": "Inverses and solving equations",
     "questions": [
      {
       "id": "mx_inv_a",
       "type": "number",
       "topic": "matrices",
       "prompt": "For M = [3 4; 1 2], the inverse is (1/det)·[d −b; −c a]. What is the top-left entry of M⁻¹?",
       "answerNumber": 1,
       "tolerance": 0,
       "answerValue": "1",
       "explain": "Swap the diagonal, negate the off-diagonal, divide by the determinant 2: top-left becomes 2/2 = 1.",
       "viz": "matInv",
       "vizHint": "Watch the inverse undo the transformation."
      },
      {
       "id": "mx_inv_check",
       "type": "truefalse",
       "topic": "matrices",
       "prompt": "Multiplying a matrix by its inverse gives the identity, in either order.",
       "statement": "Multiplying a matrix by its inverse gives the identity, in either order.",
       "answerBool": true,
       "answerValue": "TRUE",
       "explain": "MM⁻¹ = M⁻¹M = I. Inverses are the one case where matrix multiplication does commute, and that is essentially what being an inverse means.",
       "viz": "matInv"
      },
      {
       "id": "mx_solve_x",
       "type": "number",
       "topic": "matrices",
       "prompt": "Solve 3x + 4y = 10 and x + 2y = 4 using matrices. What is x?",
       "answerNumber": 2,
       "tolerance": 0,
       "answerValue": "2",
       "explain": "The system is [3 4; 1 2][x; y] = [10; 4]. The determinant is 3×2 − 4×1 = 2, so the inverse is (1/2)[2 −4; −1 3]. Multiplying: x = (2×10 − 4×4)/2 = 4/2 = 2, and y = (−1×10 + 3×4)/2 = 2/2 = 1. Check: 3(2) + 4(1) = 10. ✓",
       "viz": "solveLines",
       "vizHint": "Drag the lines; the crossing point is the solution."
      },
      {
       "id": "mx_solve_y",
       "type": "number",
       "topic": "matrices",
       "prompt": "For the same system, what is y?",
       "answerNumber": 1,
       "tolerance": 0,
       "answerValue": "1",
       "explain": "y = 1, from (−1×10 + 3×4)/2 = 1. Both original equations check out: 3(2)+4(1) = 10 and 2 + 2(1) = 4.",
       "viz": "solveLines"
      },
      {
       "id": "mx_singular_system",
       "type": "choice",
       "topic": "matrices",
       "prompt": "A 2 × 2 system has determinant zero. What does that tell you about the two lines?",
       "choices": [
        "They cross at exactly one point",
        "They are parallel — no solution, or the same line with infinitely many",
        "They are perpendicular"
       ],
       "answer": 1,
       "answerValue": "They are parallel — no solution, or the same line with infinitely many",
       "explain": "Zero determinant means the rows are multiples of each other, so the two lines have the same gradient. Either they never meet (no solutions) or they are the same line (infinitely many). Exactly one solution is precisely what a non-zero determinant guarantees.",
       "viz": "solveLines"
      }
     ]
    },
    {
     "id": "m5",
     "title": "Matrices as transformations",
     "questions": [
      {
       "id": "mx_rot90",
       "type": "choice",
       "topic": "matrices",
       "prompt": "Which matrix rotates the plane 90° anticlockwise about the origin?",
       "choices": [
        "[0 −1; 1 0]",
        "[0 1; −1 0]",
        "[−1 0; 0 −1]"
       ],
       "answer": 0,
       "answerValue": "[0 −1; 1 0]",
       "explain": "Track where the basis vectors go. (1,0) must land on (0,1) and (0,1) on (−1,0) — and those images ARE the columns of the matrix. That trick answers every transformation-matrix question without memorising anything.",
       "viz": "transformPlane",
       "vizHint": "Drag the sliders and watch the shape move."
      },
      {
       "id": "mx_reflect_det",
       "type": "number",
       "topic": "matrices",
       "prompt": "What is the determinant of the matrix that reflects in the x-axis, [1 0; 0 −1]?",
       "answerNumber": -1,
       "tolerance": 0,
       "answerValue": "-1",
       "explain": "1×(−1) − 0×0 = −1. Area is preserved (magnitude 1) but orientation is reversed (negative) — which is exactly what a reflection does.",
       "viz": "transformPlane"
      },
      {
       "id": "mx_enlarge",
       "type": "number",
       "topic": "matrices",
       "prompt": "An enlargement scale factor 3 about the origin has matrix [3 0; 0 3]. By what factor does it multiply AREA?",
       "answerNumber": 9,
       "tolerance": 0,
       "answerValue": "9",
       "explain": "det = 9. Lengths triple, so areas go up by 3² = 9. In general a 2 × 2 matrix multiplies area by |det|, which is the cleanest way to remember what a determinant is FOR.",
       "viz": "detArea"
      },
      {
       "id": "mx_compose_order",
       "type": "choice",
       "topic": "matrices",
       "prompt": "You rotate by R and then reflect by F. Which single matrix does the job?",
       "choices": [
        "RF",
        "FR",
        "R + F"
       ],
       "answer": 1,
       "answerValue": "FR",
       "explain": "FR — the one applied FIRST sits nearest the vector, on the right, because it acts on the vector first: F(Rv) = (FR)v. Reading composition left to right is the classic error, and it gives a different transformation whenever the two do not commute.",
       "viz": "transformPlane"
      },
      {
       "id": "mx_shear_area",
       "type": "number",
       "topic": "matrices",
       "prompt": "A shear has matrix [1 4; 0 1]. What is its determinant?",
       "answerNumber": 1,
       "tolerance": 0,
       "answerValue": "1",
       "explain": "1×1 − 4×0 = 1. A shear slides the plane sideways but preserves area entirely — the parallelogram leans over without getting bigger. Determinant 1 is the signature of that.",
       "viz": "detArea"
      }
     ]
    },
    {
     "id": "m6",
     "title": "Exam-level problems",
     "questions": [
      {
       "id": "mx_det_product",
       "type": "number",
       "topic": "matrices",
       "prompt": "det(A) = 3 and det(B) = 5, both 2 × 2. What is det(AB)?",
       "answerNumber": 15,
       "tolerance": 0,
       "answerValue": "15",
       "explain": "det(AB) = det(A)det(B) = 15. It follows from what determinants mean: apply one transformation that triples area, then one that quintuples it, and area is multiplied by 15. This identity is worth knowing cold — it turns many exam questions into one line.",
       "viz": "detArea"
      },
      {
       "id": "mx_det_inverse",
       "type": "number",
       "topic": "matrices",
       "prompt": "det(A) = 4. What is det(A⁻¹)? Give your answer as a decimal.",
       "answerNumber": 0.25,
       "tolerance": 0.001,
       "answerValue": "0.25",
       "explain": "Since AA⁻¹ = I and det(I) = 1, det(A)det(A⁻¹) = 1, so det(A⁻¹) = 1/4 = 0.25. The inverse must undo the area scaling."
      },
      {
       "id": "mx_det_scalar",
       "type": "number",
       "topic": "matrices",
       "prompt": "A is 2 × 2 with det(A) = 3. What is det(2A)?",
       "answerNumber": 12,
       "tolerance": 0,
       "answerValue": "12",
       "explain": "Every entry doubles, so BOTH columns double, and area scales by 2 × 2 = 4. det(2A) = 4 × 3 = 12. For an n × n matrix the factor is kⁿ — a favourite exam trap, because the instinct is to say 6.",
       "viz": "detArea"
      },
      {
       "id": "mx_lambda",
       "type": "number",
       "topic": "matrices",
       "prompt": "For what value of k is [k 3; 2 k−1] singular? Give the positive root.",
       "answerNumber": 3,
       "tolerance": 0,
       "answerValue": "3",
       "explain": "Singular means determinant zero: k(k−1) − 6 = 0, so k² − k − 6 = 0, giving (k−3)(k+2) = 0 and k = 3 or k = −2. The positive root is 3. Check: [3 3; 2 2] has rows in the ratio 1 : 1, plainly singular."
      },
      {
       "id": "mx_transpose_det",
       "type": "truefalse",
       "topic": "matrices",
       "prompt": "A matrix and its transpose have the same determinant.",
       "statement": "A matrix and its transpose have the same determinant.",
       "answerBool": true,
       "answerValue": "TRUE",
       "explain": "det(Aᵀ) = det(A) always. For a 2 × 2 it is immediate: swapping b and c leaves ad − bc alone. It is the reason you may expand a determinant along a column just as happily as along a row."
      }
     ]
    }
   ]
  },
  {
   "id": "u_algebra",
   "index": 2,
   "title": "Algebra and functions",
   "subtitle": "Indices, surds, quadratics, polynomials, inequalities.",
   "colour": "#3fb950",
   "free": true,
   "syllabus": "ESAT M1 · PAT",
   "lessons": [
    {
     "id": "a1",
     "title": "Indices and surds",
     "questions": [
      {
       "id": "al_indices",
       "type": "number",
       "topic": "algebra",
       "prompt": "Simplify (2³)⁴ ÷ 2¹⁰ as a power of 2. What is the index?",
       "answerNumber": 2,
       "tolerance": 0,
       "answerValue": "2",
       "explain": "(2³)⁴ = 2¹² because you MULTIPLY indices when raising a power to a power, then dividing subtracts: 12 − 10 = 2. The two rules get confused constantly; the safe check is to expand a small case, (2²)³ = 4³ = 64 = 2⁶."
      },
      {
       "id": "al_neg_index",
       "type": "number",
       "topic": "algebra",
       "prompt": "What is 8^(−2/3)? Give your answer as a decimal.",
       "answerNumber": 0.25,
       "tolerance": 0.001,
       "answerValue": "0.25",
       "explain": "The denominator of the fraction is a root, the numerator a power, and the minus sign flips it: 8^(1/3) = 2, squared is 4, reciprocal is 0.25. Doing the ROOT first keeps the numbers small, which is the whole trick."
      },
      {
       "id": "al_surd",
       "type": "number",
       "topic": "algebra",
       "prompt": "Rationalise 6/√3 and give the coefficient of √3.",
       "answerNumber": 2,
       "tolerance": 0,
       "answerValue": "2",
       "explain": "Multiply top and bottom by √3: 6√3/3 = 2√3, so the coefficient is 2. Rationalising never changes the value, only the form, and examiners expect the form with no surd underneath."
      },
      {
       "id": "al_surd_conj",
       "type": "number",
       "topic": "algebra",
       "prompt": "Rationalise 1/(3 − √2). The result is (3 + √2)/k. What is k?",
       "answerNumber": 7,
       "tolerance": 0,
       "answerValue": "7",
       "explain": "Multiply by the conjugate 3 + √2. The bottom becomes 3² − (√2)² = 9 − 2 = 7, because the cross terms cancel. That difference-of-two-squares cancellation is the entire reason conjugates work."
      },
      {
       "id": "al_surd_add",
       "type": "truefalse",
       "topic": "algebra",
       "prompt": "√9 + √16 is equal to √25.",
       "statement": "√9 + √16 is equal to √25.",
       "answerBool": false,
       "answerValue": "FALSE",
       "explain": "3 + 4 = 7, but √25 = 5. Roots do not distribute over addition. They DO distribute over multiplication — √9 × √16 = √144 = 12 — and mixing the two up is one of the most common errors in the paper."
      }
     ]
    },
    {
     "id": "a2",
     "title": "Quadratics",
     "questions": [
      {
       "id": "al_quad_roots",
       "type": "number",
       "topic": "algebra",
       "prompt": "How many real roots does x² − 6x + 9 = 0 have?",
       "answerNumber": 1,
       "tolerance": 0,
       "answerValue": "1",
       "explain": "The discriminant is 36 − 36 = 0, so there is one repeated root, x = 3. b² − 4ac decides it: positive gives two, zero gives one, negative gives none."
      },
      {
       "id": "al_complete",
       "type": "number",
       "topic": "algebra",
       "prompt": "Write x² + 8x + 3 as (x + p)² + q. What is q?",
       "answerNumber": -13,
       "tolerance": 0,
       "answerValue": "-13",
       "explain": "Half of 8 is 4, so (x+4)² = x² + 8x + 16, which overshoots by 13. Hence (x+4)² − 13 and q = −13. Completing the square hands you the minimum point directly: (−4, −13)."
      },
      {
       "id": "al_sum_roots",
       "type": "number",
       "topic": "algebra",
       "prompt": "For 2x² − 10x + 3 = 0, what is the SUM of the roots?",
       "answerNumber": 5,
       "tolerance": 0,
       "answerValue": "5",
       "explain": "Sum of roots is −b/a = 10/2 = 5, and the product is c/a = 1.5. You never have to solve the quadratic to answer this, which is exactly why it appears on a multiple-choice paper."
      },
      {
       "id": "al_disc_k",
       "type": "number",
       "topic": "algebra",
       "prompt": "For what value of k does x² + kx + 9 = 0 have exactly one root? Give the positive value.",
       "answerNumber": 6,
       "tolerance": 0,
       "answerValue": "6",
       "explain": "One root means the discriminant is zero: k² − 36 = 0, so k = ±6. The positive value is 6, giving (x+3)² = 0."
      },
      {
       "id": "al_disc",
       "type": "truefalse",
       "topic": "algebra",
       "prompt": "If a quadratic has a negative discriminant its graph never crosses the x-axis.",
       "statement": "If a quadratic has a negative discriminant its graph never crosses the x-axis.",
       "answerBool": true,
       "answerValue": "TRUE",
       "explain": "No real roots means no crossings — the parabola sits entirely above or entirely below the axis, depending on the sign of a. Sketching this is usually faster than any algebra."
      }
     ]
    },
    {
     "id": "a3",
     "title": "Polynomials",
     "questions": [
      {
       "id": "al_factor_thm",
       "type": "number",
       "topic": "algebra",
       "prompt": "f(x) = x³ − 4x² + x + 6. What is f(2)?",
       "answerNumber": 0,
       "tolerance": 0,
       "answerValue": "0",
       "explain": "8 − 16 + 2 + 6 = 0. Since f(2) = 0, the factor theorem says (x − 2) is a factor. Hunting for a root among the factors of the constant term is the standard opening move on a cubic."
      },
      {
       "id": "al_remainder",
       "type": "number",
       "topic": "algebra",
       "prompt": "Find the remainder when x³ + 2x − 5 is divided by (x − 1).",
       "answerNumber": -2,
       "tolerance": 0,
       "answerValue": "-2",
       "explain": "The remainder theorem: just evaluate at x = 1, giving 1 + 2 − 5 = −2. No long division required, which is the point of the theorem."
      },
      {
       "id": "al_cubic_roots",
       "type": "number",
       "topic": "algebra",
       "prompt": "x³ − 4x² + x + 6 factorises as (x−2)(x−3)(x+1). What is the sum of its roots?",
       "answerNumber": 4,
       "tolerance": 0,
       "answerValue": "4",
       "explain": "2 + 3 − 1 = 4, which also equals −b/a = 4 for a cubic. The root-coefficient relations carry over from quadratics and are worth knowing for all three."
      },
      {
       "id": "al_expand",
       "type": "number",
       "topic": "algebra",
       "prompt": "In the expansion of (1 + x)⁵, what is the coefficient of x²?",
       "answerNumber": 10,
       "tolerance": 0,
       "answerValue": "10",
       "explain": "It is the binomial coefficient 5C2 = 10. The whole row is 1, 5, 10, 10, 5, 1 — the sixth row of Pascal's triangle, which is the fastest way to write down any small expansion."
      },
      {
       "id": "al_binom_term",
       "type": "number",
       "topic": "algebra",
       "prompt": "In the expansion of (2 + x)⁴, what is the coefficient of x²?",
       "answerNumber": 24,
       "tolerance": 0,
       "answerValue": "24",
       "explain": "4C2 × 2² = 6 × 4 = 24. The general term is nCr × a^(n−r) × b^r; forgetting to raise the 2 to a power is the standard slip."
      }
     ]
    },
    {
     "id": "a4",
     "title": "Inequalities and simultaneous equations",
     "questions": [
      {
       "id": "al_ineq",
       "type": "number",
       "topic": "algebra",
       "prompt": "Solve x² − 5x + 6 < 0. The solution is a < x < b. What is b?",
       "answerNumber": 3,
       "tolerance": 0,
       "answerValue": "3",
       "explain": "The roots are 2 and 3, and a positive parabola is BELOW the axis strictly between its roots, so 2 < x < 3 and b = 3. Sketching beats sign tables here."
      },
      {
       "id": "al_ineq_flip",
       "type": "number",
       "topic": "algebra",
       "prompt": "Solve −3x > 12. The solution is x < k. What is k?",
       "answerNumber": -4,
       "tolerance": 0,
       "answerValue": "-4",
       "explain": "Dividing by a negative reverses the inequality: x < −4. This is the single most-punished slip in the topic, and it is worth testing your answer with one value — x = −5 gives 15 > 12. ✓"
      },
      {
       "id": "al_sim_x",
       "type": "number",
       "topic": "algebra",
       "prompt": "Solve 2x + y = 7 and x − y = 2 simultaneously. What is x?",
       "answerNumber": 3,
       "tolerance": 0,
       "answerValue": "3",
       "explain": "Adding the equations eliminates y: 3x = 9, so x = 3 and y = 1. Check both: 6 + 1 = 7 ✓ and 3 − 1 = 2 ✓."
      },
      {
       "id": "al_sim_quad",
       "type": "number",
       "topic": "algebra",
       "prompt": "y = x² and y = x + 6 meet at two points. What is the LARGER x-coordinate?",
       "answerNumber": 3,
       "tolerance": 0,
       "answerValue": "3",
       "explain": "x² = x + 6 gives x² − x − 6 = 0, so (x−3)(x+2) = 0 and x = 3 or −2. The larger is 3, where y = 9."
      },
      {
       "id": "al_ineq_square",
       "type": "truefalse",
       "topic": "algebra",
       "prompt": "If x² > 9 then x > 3.",
       "statement": "If x² > 9 then x > 3.",
       "answerBool": false,
       "answerValue": "FALSE",
       "explain": "x could be less than −3: x = −4 gives 16 > 9. The full solution is x > 3 OR x < −3. Squaring loses sign information, and forgetting the negative branch is a favourite trap."
      }
     ]
    },
    {
     "id": "a5",
     "title": "Exam-level algebra",
     "questions": [
      {
       "id": "al_exam_disc",
       "type": "number",
       "topic": "algebra",
       "prompt": "The line y = mx − 1 is a tangent to y = x². Find the positive value of m.",
       "answerNumber": 2,
       "tolerance": 0,
       "answerValue": "2",
       "explain": "Setting them equal: x² − mx + 1 = 0. A tangent meets the curve exactly once, so the discriminant is zero: m² − 4 = 0 and m = ±2. The positive value is 2, touching at x = 1 where both give y = 1. Note the sign of the constant matters: with y = mx + 1 the discriminant is m² + 4, which is never zero, so that line always CROSSES the parabola twice."
      },
      {
       "id": "al_exam_surd",
       "type": "number",
       "topic": "algebra",
       "prompt": "Simplify √50 + √18 as k√2. What is k?",
       "answerNumber": 8,
       "tolerance": 0,
       "answerValue": "8",
       "explain": "√50 = 5√2 and √18 = 3√2, so the sum is 8√2 and k = 8. Always pull out the largest square factor first; the surds then combine like ordinary terms."
      },
      {
       "id": "al_exam_poly",
       "type": "number",
       "topic": "algebra",
       "prompt": "x³ + ax² − 4x − 12 has (x − 2) as a factor. Find a.",
       "answerNumber": 3,
       "tolerance": 0,
       "answerValue": "3",
       "explain": "The factor theorem says f(2) = 0, so 8 + 4a − 8 − 12 = 0, giving 4a = 12 and a = 3. Substituting back to check: 8 + 12 − 8 − 12 = 0 ✓. That substitution takes five seconds and catches every arithmetic slip in this kind of question."
      },
      {
       "id": "al_exam_index",
       "type": "number",
       "topic": "algebra",
       "prompt": "Solve 3^(2x) = 81. What is x?",
       "answerNumber": 2,
       "tolerance": 0,
       "answerValue": "2",
       "explain": "81 = 3⁴, so 2x = 4 and x = 2. Writing both sides to the same base turns an exponential equation into a linear one, and is almost always quicker than logs on an entrance paper."
      },
      {
       "id": "al_exam_frac",
       "type": "number",
       "topic": "algebra",
       "prompt": "Solve 1/(x−1) = 4/(x+2). What is x?",
       "answerNumber": 2,
       "tolerance": 0,
       "answerValue": "2",
       "explain": "Cross-multiplying: x + 2 = 4x − 4, so 3x = 6 and x = 2. Check the value does not make a denominator zero — here x = 2 gives 1/1 = 4/4 ✓."
      }
     ]
    }
   ]
  },
  {
   "id": "u_calculus",
   "index": 3,
   "title": "Differentiation",
   "subtitle": "Rates of change, stationary points, optimisation.",
   "colour": "#d29922",
   "free": false,
   "syllabus": "ESAT M1 · PAT",
   "lessons": [
    {
     "id": "c1",
     "title": "The idea of a derivative",
     "questions": [
      {
       "id": "ca_power",
       "type": "number",
       "topic": "calculus",
       "prompt": "Differentiate y = 4x³. What is dy/dx when x = 2?",
       "answerNumber": 48,
       "tolerance": 0,
       "answerValue": "48",
       "explain": "dy/dx = 12x², and 12 × 4 = 48. Multiply by the index, then drop it by one. The derivative is a FUNCTION: feed it an x and it returns the gradient there."
      },
      {
       "id": "ca_constant",
       "type": "number",
       "topic": "calculus",
       "prompt": "Differentiate y = 7. What is dy/dx?",
       "answerNumber": 0,
       "tolerance": 0,
       "answerValue": "0",
       "explain": "Zero. A constant function is a horizontal line, and a horizontal line has no gradient anywhere. This is why the constant vanishes in differentiation and has to be recovered when integrating."
      },
      {
       "id": "ca_sum",
       "type": "number",
       "topic": "calculus",
       "prompt": "Differentiate y = x³ − 5x + 2 and give dy/dx at x = 1.",
       "answerNumber": -2,
       "tolerance": 0,
       "answerValue": "-2",
       "explain": "dy/dx = 3x² − 5, which is 3 − 5 = −2 at x = 1. Differentiation goes term by term, and the negative gradient tells you the curve is falling there."
      },
      {
       "id": "ca_neg_power",
       "type": "number",
       "topic": "calculus",
       "prompt": "Differentiate y = 1/x, i.e. x⁻¹. What is dy/dx at x = 2?",
       "answerNumber": -0.25,
       "tolerance": 0.001,
       "answerValue": "-0.25",
       "explain": "dy/dx = −x⁻² = −1/x², which is −1/4 at x = 2. The rule is the same for negative indices; write the term as a power first and the rule applies unchanged."
      },
      {
       "id": "ca_grad_meaning",
       "type": "truefalse",
       "topic": "calculus",
       "prompt": "Where a curve is falling, its derivative is negative.",
       "statement": "Where a curve is falling, its derivative is negative.",
       "answerBool": true,
       "answerValue": "TRUE",
       "explain": "The derivative IS the gradient of the tangent. Falling means the tangent slopes downward, which is a negative gradient. Reading a sign off a sketch is often all a question needs."
      }
     ]
    },
    {
     "id": "c2",
     "title": "Rules",
     "questions": [
      {
       "id": "ca_chain",
       "type": "number",
       "topic": "calculus",
       "prompt": "Differentiate y = (2x + 1)⁵ and give dy/dx at x = 0.",
       "answerNumber": 10,
       "tolerance": 0,
       "answerValue": "10",
       "explain": "Chain rule: 5(2x+1)⁴ × 2 = 10(2x+1)⁴, which is 10 at x = 0. Differentiate the outside, leave the inside alone, then multiply by the derivative of the inside."
      },
      {
       "id": "ca_product",
       "type": "number",
       "topic": "calculus",
       "prompt": "Differentiate y = x²(x + 3) and give dy/dx at x = 1.",
       "answerNumber": 9,
       "tolerance": 0,
       "answerValue": "9",
       "explain": "Expanding first gives y = x³ + 3x², so dy/dx = 3x² + 6x = 9 at x = 1. The product rule gives the same answer; expanding is safer when the expansion is easy."
      },
      {
       "id": "ca_quotient",
       "type": "number",
       "topic": "calculus",
       "prompt": "Differentiate y = (x + 1)/x and give dy/dx at x = 1.",
       "answerNumber": -1,
       "tolerance": 0,
       "answerValue": "-1",
       "explain": "Rewrite as 1 + x⁻¹, so dy/dx = −x⁻² = −1 at x = 1. Splitting the fraction avoids the quotient rule entirely — always worth checking whether you can."
      },
      {
       "id": "ca_second",
       "type": "number",
       "topic": "calculus",
       "prompt": "y = x³ − 3x. What is d²y/dx² at x = 2?",
       "answerNumber": 12,
       "tolerance": 0,
       "answerValue": "12",
       "explain": "dy/dx = 3x² − 3, and differentiating again gives 6x = 12 at x = 2. The second derivative measures how the gradient itself is changing — the curvature."
      },
      {
       "id": "ca_chain_forget",
       "type": "truefalse",
       "topic": "calculus",
       "prompt": "The derivative of (3x + 2)⁴ is 4(3x + 2)³.",
       "statement": "The derivative of (3x + 2)⁴ is 4(3x + 2)³.",
       "answerBool": false,
       "answerValue": "FALSE",
       "explain": "That misses the inner derivative. The correct answer is 4(3x+2)³ × 3 = 12(3x+2)³. Forgetting the factor from the inside is the commonest chain-rule error there is."
      }
     ]
    },
    {
     "id": "c3",
     "title": "Stationary points",
     "questions": [
      {
       "id": "ca_stationary",
       "type": "number",
       "topic": "calculus",
       "prompt": "y = x² − 6x + 5. At what value of x is the stationary point?",
       "answerNumber": 3,
       "tolerance": 0,
       "answerValue": "3",
       "explain": "dy/dx = 2x − 6 = 0 gives x = 3. The second derivative is 2, positive, so it is a minimum — at (3, −4)."
      },
      {
       "id": "ca_two_stat",
       "type": "number",
       "topic": "calculus",
       "prompt": "y = x³ − 3x has two stationary points. What is the LARGER x-value?",
       "answerNumber": 1,
       "tolerance": 0,
       "answerValue": "1",
       "explain": "dy/dx = 3x² − 3 = 0 gives x = ±1. The larger is 1, where the second derivative 6x is positive — a minimum. At x = −1 it is negative, a maximum."
      },
      {
       "id": "ca_nature",
       "type": "choice",
       "topic": "calculus",
       "prompt": "At a stationary point the second derivative is negative. What kind of point is it?",
       "choices": [
        "A minimum",
        "A maximum",
        "A point of inflection"
       ],
       "answer": 1,
       "answerValue": "A maximum",
       "explain": "Negative second derivative means the gradient is decreasing through the point — the curve is bending downward, so the stationary point is a maximum."
      },
      {
       "id": "ca_optimise",
       "type": "number",
       "topic": "calculus",
       "prompt": "A rectangle has perimeter 20. What is its greatest possible area?",
       "answerNumber": 25,
       "tolerance": 0,
       "answerValue": "25",
       "explain": "With sides x and 10 − x, area A = x(10 − x) = 10x − x². dA/dx = 10 − 2x = 0 gives x = 5, so the rectangle is a 5 by 5 square with area 25. Optimisation questions are nearly always this shape: write the thing you want in ONE variable, then differentiate."
      },
      {
       "id": "ca_box",
       "type": "number",
       "topic": "calculus",
       "prompt": "An open box is made from a square of side 12 by cutting x from each corner. V = x(12 − 2x)². What x maximises the volume?",
       "answerNumber": 2,
       "tolerance": 0,
       "answerValue": "2",
       "explain": "dV/dx = (12−2x)² + x·2(12−2x)(−2) = (12−2x)(12 − 6x), zero at x = 2 or x = 6. x = 6 gives zero volume, so the maximum is at x = 2, giving V = 2 × 64 = 128. Always reject the root that makes no physical sense."
      }
     ]
    },
    {
     "id": "c4",
     "title": "Tangents and rates",
     "questions": [
      {
       "id": "ca_tangent",
       "type": "number",
       "topic": "calculus",
       "prompt": "Find the gradient of the tangent to y = x³ − 2x at x = 1.",
       "answerNumber": 1,
       "tolerance": 0,
       "answerValue": "1",
       "explain": "dy/dx = 3x² − 2, which is 3 − 2 = 1 at x = 1. The derivative IS the gradient function: feed it an x and it hands back the slope of the tangent at that point."
      },
      {
       "id": "ca_normal",
       "type": "number",
       "topic": "calculus",
       "prompt": "The tangent to a curve has gradient 4. What is the gradient of the normal there? Give it as a decimal.",
       "answerNumber": -0.25,
       "tolerance": 0.001,
       "answerValue": "-0.25",
       "explain": "The normal is perpendicular, so its gradient is −1/4 = −0.25. Perpendicular gradients multiply to −1, which is worth checking on every normal question."
      },
      {
       "id": "ca_tangent_eq",
       "type": "number",
       "topic": "calculus",
       "prompt": "y = x² at x = 3. The tangent is y = 6x + c. What is c?",
       "answerNumber": -9,
       "tolerance": 0,
       "answerValue": "-9",
       "explain": "The gradient is 2x = 6 and the point is (3, 9), so 9 = 18 + c and c = −9. The tangent is y = 6x − 9."
      },
      {
       "id": "ca_rate",
       "type": "number",
       "topic": "calculus",
       "prompt": "A balloon's volume is V = 4t³. What is dV/dt at t = 2?",
       "answerNumber": 48,
       "tolerance": 0,
       "answerValue": "48",
       "explain": "dV/dt = 12t² = 48 at t = 2. A derivative with respect to TIME is a rate of change, which is what most of the physics on the paper is really asking about."
      },
      {
       "id": "ca_zero_grad",
       "type": "truefalse",
       "topic": "calculus",
       "prompt": "If dy/dx = 0 at a point, the curve must have a maximum or minimum there.",
       "statement": "If dy/dx = 0 at a point, the curve must have a maximum or minimum there.",
       "answerBool": false,
       "answerValue": "FALSE",
       "explain": "It could be a point of inflection — y = x³ at x = 0 has zero gradient but is neither a maximum nor a minimum. Zero gradient is necessary for a turning point, not sufficient."
      }
     ]
    },
    {
     "id": "c5",
     "title": "Exam-level calculus",
     "questions": [
      {
       "id": "ca_exam_area",
       "type": "number",
       "topic": "calculus",
       "prompt": "A cylinder has volume 16π. Its surface area is minimised when the radius is r. What is r?",
       "answerNumber": 2,
       "tolerance": 0,
       "answerValue": "2",
       "explain": "With V = πr²h = 16π, h = 16/r². Surface area A = 2πr² + 2πrh = 2πr² + 32π/r. dA/dr = 4πr − 32π/r² = 0 gives r³ = 8, so r = 2 and h = 4 — the height is the diameter, which is the classic result."
      },
      {
       "id": "ca_exam_curve",
       "type": "number",
       "topic": "calculus",
       "prompt": "y = x³ − 6x² + 9x. At how many points is the tangent horizontal?",
       "answerNumber": 2,
       "tolerance": 0,
       "answerValue": "2",
       "explain": "dy/dx = 3x² − 12x + 9 = 3(x−1)(x−3), zero at x = 1 and x = 3. Two points: a maximum at (1, 4) and a minimum at (3, 0)."
      },
      {
       "id": "ca_exam_inflect",
       "type": "number",
       "topic": "calculus",
       "prompt": "y = x³ − 6x². Find the x-coordinate of the point of inflection.",
       "answerNumber": 2,
       "tolerance": 0,
       "answerValue": "2",
       "explain": "d²y/dx² = 6x − 12 = 0 at x = 2, and the second derivative changes sign there, so it is a genuine inflection. Checking the SIGN CHANGE matters: a zero second derivative alone is not enough."
      },
      {
       "id": "ca_exam_chain2",
       "type": "number",
       "topic": "calculus",
       "prompt": "Differentiate y = (x² + 1)³ and give dy/dx at x = 1.",
       "answerNumber": 24,
       "tolerance": 0,
       "answerValue": "24",
       "explain": "dy/dx = 3(x²+1)² × 2x = 6x(x²+1)², which at x = 1 is 6 × 4 = 24."
      },
      {
       "id": "ca_exam_ladder",
       "type": "number",
       "topic": "calculus",
       "prompt": "y = 2x³ − 9x² + 12x. The stationary values are y = a and y = b. What is the LARGER of the two y-values?",
       "answerNumber": 5,
       "tolerance": 0,
       "answerValue": "5",
       "explain": "dy/dx = 6x² − 18x + 12 = 6(x−1)(x−2), so x = 1 gives y = 5 and x = 2 gives y = 4. The larger stationary value is 5 — and note it is a MAXIMUM at the smaller x, which a sketch makes obvious."
      }
     ]
    }
   ]
  },
  {
   "id": "u_integration",
   "index": 4,
   "title": "Integration",
   "subtitle": "Reversing differentiation, area, volumes of revolution.",
   "colour": "#2ea043",
   "free": false,
   "syllabus": "ESAT M1 · PAT",
   "lessons": [
    {
     "id": "i1",
     "title": "Reversing differentiation",
     "questions": [
      {
       "id": "in_power",
       "type": "number",
       "topic": "integration",
       "prompt": "Integrate 3x². What is the coefficient of x³ in the result?",
       "answerNumber": 1,
       "tolerance": 0,
       "answerValue": "1",
       "explain": "Raise the index by one and divide by the new index: 3x³/3 = x³, so the coefficient is 1. Integration is differentiation run backwards, which is why the check is always to differentiate your answer."
      },
      {
       "id": "in_constant",
       "type": "number",
       "topic": "integration",
       "prompt": "Integrate 5 with respect to x. What is the coefficient of x?",
       "answerNumber": 5,
       "tolerance": 0,
       "answerValue": "5",
       "explain": "∫5 dx = 5x + c. A constant integrates to a term linear in x, and the arbitrary constant c appears because differentiating any constant gives zero."
      },
      {
       "id": "in_plus_c",
       "type": "truefalse",
       "topic": "integration",
       "prompt": "An indefinite integral needs an arbitrary constant.",
       "statement": "An indefinite integral needs an arbitrary constant.",
       "answerBool": true,
       "answerValue": "TRUE",
       "explain": "Infinitely many functions share the same derivative, differing only by a constant, so + c records that. Dropping it is a guaranteed lost mark on an indefinite integral."
      },
      {
       "id": "in_sum",
       "type": "number",
       "topic": "integration",
       "prompt": "Integrate 6x + 4. Evaluate the result at x = 2, taking c = 0.",
       "answerNumber": 20,
       "tolerance": 0,
       "answerValue": "20",
       "explain": "∫(6x+4)dx = 3x² + 4x + c, which at x = 2 is 12 + 8 = 20. Each term integrates separately, exactly as each term differentiates separately — integration is linear."
      },
      {
       "id": "in_neg",
       "type": "number",
       "topic": "integration",
       "prompt": "Integrate x⁻² . The result is −x⁻¹ + c. What is its value at x = 2? Give a decimal.",
       "answerNumber": -0.5,
       "tolerance": 0.001,
       "answerValue": "-0.5",
       "explain": "−1/x = −0.5 at x = 2. The power rule works for every index except −1, where the integral is ln|x| instead — the one exception worth memorising."
      }
     ]
    },
    {
     "id": "i2",
     "title": "Definite integrals and area",
     "questions": [
      {
       "id": "in_def",
       "type": "number",
       "topic": "integration",
       "prompt": "Evaluate ∫ from 0 to 3 of x² dx.",
       "answerNumber": 9,
       "tolerance": 0,
       "answerValue": "9",
       "explain": "[x³/3] from 0 to 3 = 27/3 − 0 = 9. A definite integral needs no constant, because it cancels when you subtract the two limits."
      },
      {
       "id": "in_area",
       "type": "number",
       "topic": "integration",
       "prompt": "Find the area between y = 2x and the x-axis from x = 1 to x = 4.",
       "answerNumber": 15,
       "tolerance": 0,
       "answerValue": "15",
       "explain": "[x²] from 1 to 4 = 16 − 1 = 15. Check it geometrically: it is a trapezium with parallel sides 2 and 8 and width 3, area ½(2+8)(3) = 15 ✓."
      },
      {
       "id": "in_between",
       "type": "number",
       "topic": "integration",
       "prompt": "Find the area between y = x² and y = x from x = 0 to x = 1. The answer is 1/k. What is k?",
       "answerNumber": 6,
       "tolerance": 0,
       "answerValue": "6",
       "explain": "∫(x − x²)dx = [x²/2 − x³/3] = 1/2 − 1/3 = 1/6, so k = 6. Always subtract the LOWER curve from the upper one; getting the order wrong just flips the sign."
      },
      {
       "id": "in_negative",
       "type": "truefalse",
       "topic": "integration",
       "prompt": "A definite integral can come out negative.",
       "statement": "A definite integral can come out negative.",
       "answerBool": true,
       "answerValue": "TRUE",
       "explain": "Where the curve is below the axis the integral is negative. That is why an AREA question needs the region split at every crossing — otherwise positive and negative parts cancel and you understate it."
      },
      {
       "id": "in_limits_swap",
       "type": "number",
       "topic": "integration",
       "prompt": "If ∫ from 1 to 5 of f(x) dx = 12, what is ∫ from 5 to 1 of f(x) dx?",
       "answerNumber": -12,
       "tolerance": 0,
       "answerValue": "-12",
       "explain": "Swapping the limits negates the integral. It follows straight from F(b) − F(a) becoming F(a) − F(b)."
      }
     ]
    },
    {
     "id": "i3",
     "title": "Exam-level integration",
     "questions": [
      {
       "id": "in_exam_area",
       "type": "number",
       "topic": "integration",
       "prompt": "The curve y = x(4 − x) meets the x-axis at 0 and 4. What is the area enclosed? The answer is k/3. What is k?",
       "answerNumber": 32,
       "tolerance": 0,
       "answerValue": "32",
       "explain": "∫(4x − x²)dx from 0 to 4 = [2x² − x³/3] = 32 − 64/3 = 32/3, so k = 32. Sketching first tells you the curve is above the axis throughout, so no splitting is needed."
      },
      {
       "id": "in_exam_volume",
       "type": "number",
       "topic": "integration",
       "prompt": "y = x is rotated about the x-axis from 0 to 3. The volume is kπ. What is k?",
       "answerNumber": 9,
       "tolerance": 0,
       "answerValue": "9",
       "explain": "V = π∫y² dx = π∫x² dx from 0 to 3 = π × 9, so k = 9. It is a cone of radius 3 and height 3: ⅓π(9)(3) = 9π ✓."
      },
      {
       "id": "in_exam_kinematics",
       "type": "number",
       "topic": "integration",
       "prompt": "A particle has velocity v = 3t². How far does it travel between t = 0 and t = 2?",
       "answerNumber": 8,
       "tolerance": 0,
       "answerValue": "8",
       "explain": "Distance is ∫v dt = [t³] from 0 to 2 = 8. Integrating velocity gives displacement, and differentiating it gives acceleration — the same ladder the mechanics questions use."
      },
      {
       "id": "in_exam_mean",
       "type": "number",
       "topic": "integration",
       "prompt": "What is the mean value of y = x² between x = 0 and x = 3?",
       "answerNumber": 3,
       "tolerance": 0,
       "answerValue": "3",
       "explain": "Mean = (1/(b−a))∫y dx = (1/3) × 9 = 3. The mean value is the height of the rectangle with the same area over the same width."
      },
      {
       "id": "in_exam_split",
       "type": "number",
       "topic": "integration",
       "prompt": "y = x³ from x = −2 to 2. What is the value of the definite integral?",
       "answerNumber": 0,
       "tolerance": 0,
       "answerValue": "0",
       "explain": "Zero, because x³ is an odd function and the negative area from −2 to 0 exactly cancels the positive area from 0 to 2. The AREA, though, is 8 — which is what the question would ask for if it wanted a non-zero answer. Spotting odd symmetry saves the whole calculation."
      }
     ]
    }
   ]
  },
  {
   "id": "u_mechanics",
   "index": 5,
   "title": "Mechanics",
   "subtitle": "Kinematics, forces, momentum, energy.",
   "colour": "#f85149",
   "free": false,
   "syllabus": "ESAT Physics · PAT",
   "lessons": [
    {
     "id": "p1",
     "title": "Motion and forces",
     "questions": [
      {
       "id": "me_suvat",
       "type": "number",
       "topic": "mechanics",
       "prompt": "A ball is dropped from rest. Taking g = 10 m/s², how fast is it moving after 3 s, in m/s?",
       "answerNumber": 30,
       "tolerance": 0,
       "answerValue": "30",
       "explain": "v = u + at = 0 + 10×3 = 30 m/s. With u = 0 the suvat equations become very short — worth spotting."
      },
      {
       "id": "me_distance",
       "type": "number",
       "topic": "mechanics",
       "prompt": "Same ball, same g = 10. How far has it fallen in 3 s, in metres?",
       "answerNumber": 45,
       "tolerance": 0,
       "answerValue": "45",
       "explain": "s = ut + ½at² = 0 + ½×10×9 = 45 m. Distance grows with the SQUARE of time, which is why the last second of a fall covers the most ground."
      },
      {
       "id": "me_newton",
       "type": "number",
       "topic": "mechanics",
       "prompt": "A 4 kg mass accelerates at 2.5 m/s². What resultant force acts on it, in newtons?",
       "answerNumber": 10,
       "tolerance": 0,
       "answerValue": "10",
       "explain": "F = ma = 4 × 2.5 = 10 N. The word RESULTANT matters: it is the vector sum of every force, not any single one."
      },
      {
       "id": "me_momentum",
       "type": "number",
       "topic": "mechanics",
       "prompt": "A 2 kg trolley at 3 m/s hits a stationary 1 kg trolley and they move off together. What is their common speed, in m/s?",
       "answerNumber": 2,
       "tolerance": 0,
       "answerValue": "2",
       "explain": "Momentum before = 2×3 = 6 kg m/s. After, the combined mass is 3 kg, so v = 6/3 = 2 m/s. Momentum is conserved in every collision; kinetic energy is not."
      },
      {
       "id": "me_ke_conserved",
       "type": "truefalse",
       "topic": "mechanics",
       "prompt": "Kinetic energy is conserved when two objects stick together in a collision.",
       "statement": "Kinetic energy is conserved when two objects stick together in a collision.",
       "answerBool": false,
       "answerValue": "FALSE",
       "explain": "That is a perfectly inelastic collision — momentum is conserved, kinetic energy is not. Some of it becomes heat, sound and deformation. Here: 9 J before, 6 J after."
      }
     ]
    }
   ]
  },
  {
   "id": "u_electricity",
   "index": 6,
   "title": "Electricity",
   "subtitle": "Current, resistance, circuits, power.",
   "colour": "#a371f7",
   "free": false,
   "syllabus": "ESAT Physics · PAT",
   "lessons": [
    {
     "id": "e1",
     "title": "Circuits",
     "questions": [
      {
       "id": "el_ohm",
       "type": "number",
       "topic": "electricity",
       "prompt": "A 12 V supply drives 3 A through a resistor. What is its resistance, in ohms?",
       "answerNumber": 4,
       "tolerance": 0,
       "answerValue": "4",
       "explain": "R = V/I = 12/3 = 4 Ω. Ohm's law rearranges three ways and the exam will use all of them, so it is worth being able to write any one of V, I, R in terms of the other two without stopping to think."
      },
      {
       "id": "el_series",
       "type": "number",
       "topic": "electricity",
       "prompt": "Resistors of 3 Ω and 5 Ω in series. What is the total resistance, in ohms?",
       "answerNumber": 8,
       "tolerance": 0,
       "answerValue": "8",
       "explain": "In series resistances simply add: 8 Ω. The same current passes through both."
      },
      {
       "id": "el_parallel",
       "type": "number",
       "topic": "electricity",
       "prompt": "Two 6 Ω resistors in parallel. What is the total resistance, in ohms?",
       "answerNumber": 3,
       "tolerance": 0,
       "answerValue": "3",
       "explain": "1/R = 1/6 + 1/6 = 1/3, so R = 3 Ω. Two equal resistors in parallel always give half of one — a shortcut worth having."
      },
      {
       "id": "el_power",
       "type": "number",
       "topic": "electricity",
       "prompt": "A 240 V kettle draws 8 A. What is its power, in watts?",
       "answerNumber": 1920,
       "tolerance": 0,
       "answerValue": "1920",
       "explain": "P = VI = 240 × 8 = 1920 W, near enough 2 kW. The other two forms, P = I²R and P = V²/R, follow by substituting Ohm's law and are often quicker when you know the resistance instead of one of the other quantities."
      },
      {
       "id": "el_parallel_less",
       "type": "truefalse",
       "topic": "electricity",
       "prompt": "Adding a resistor in parallel always decreases the total resistance.",
       "statement": "Adding a resistor in parallel always decreases the total resistance.",
       "answerBool": true,
       "answerValue": "TRUE",
       "explain": "Another parallel path gives the current somewhere else to go, so the combination always conducts better than the best single branch."
      }
     ]
    }
   ]
  }
 ]
};
